name: run-tests

on: push

jobs:
  run_tests:
    strategy:
      matrix:
        python-version: [3.10, 3.11]
        os: [macos-12, windows-2022]
    name: create_release
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Execute tests
        run: |
          python -m unittest discover tests
