name: run-tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  run_tests:
    name: Run unittests
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        os: [macos-14] # windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install requirements
        run: |
          python -V
          pip install -e .[test]
      - name: Execute tests
        run: |
          python -m unittest discover tests
